# Generated by Django 3.1.7 on 2021-03-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodOrdering', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
