# Generated by Django 3.1.7 on 2021-03-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='CustomerProfile',
        ),
        migrations.RenameModel(
            old_name='Delivery',
            new_name='DeliveryProfile',
        ),
        migrations.RenameModel(
            old_name='Restaurant',
            new_name='RestaurantProfile',
        ),
        migrations.AddField(
            model_name='dish',
            name='picture',
            field=models.ImageField(default='', upload_to='Dishes/'),
            preserve_default=False,
        ),
    ]
