# Generated by Django 3.1.7 on 2021-04-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='allergen',
            field=models.ManyToManyField(blank=True, to='personal.Allergen'),
        ),
        migrations.CreateModel(
            name='DishAndAllergen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen', models.ManyToManyField(blank=True, to='personal.Allergen')),
                ('dish', models.ManyToManyField(blank=True, to='personal.Dish')),
            ],
        ),
    ]
