# Generated by Django 3.1.7 on 2021-04-01 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20210401_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='allergen',
        ),
    ]
