# Generated by Django 3.1.7 on 2021-03-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_types_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='Price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='discount_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
