# Generated by Django 3.1.7 on 2021-03-27 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20210327_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryprofile',
            name='delivery_time_frame',
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='work_end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryprofile',
            name='work_start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
