# Generated by Django 3.1.7 on 2021-04-06 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20210403_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.styles'),
        ),
    ]
