# Generated by Django 3.1.7 on 2021-03-28 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal', '0005_auto_20210327_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10)),
                ('work_start_time', models.TimeField()),
                ('work_end_time', models.TimeField()),
                ('cityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.city')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Auth.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DeliveryProfile',
        ),
    ]
