# Generated by Django 3.1.7 on 2021-04-06 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_auto_20210406_0657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courierprofile',
            old_name='cityID',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='customerprofile',
            old_name='cityID',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='restaurantprofile',
            old_name='cityID',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='restaurantprofile',
            old_name='styleID',
            new_name='style',
        ),
    ]
