# Generated by Django 3.1.7 on 2021-04-06 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_auto_20210406_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantprofile',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.styles'),
        ),
    ]
