# Generated by Django 3.1.7 on 2021-04-07 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_auto_20210406_0913'),
        ('personal', '0007_auto_20210406_0658'),
        ('personal', '0005_auto_20210403_1456'),
    ]

    operations = [
    ]
