# Generated by Django 3.1.7 on 2021-03-28 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_auto_20210328_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='allergen_free',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal.allergenfree'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='picture',
            field=models.ImageField(upload_to='dishes/'),
        ),
    ]
