# Generated by Django 3.1.7 on 2021-04-07 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_merge_20210407_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='allergen',
            field=models.ManyToManyField(blank=True, null=True, to='personal.Allergen'),
        ),
        migrations.DeleteModel(
            name='DishAndAllergen',
        ),
    ]
