# Generated by Django 3.1.7 on 2021-03-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_auto_20210328_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='discount_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
