# Generated by Django 3.1.7 on 2021-04-07 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0012_remove_cart_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishtocart',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
