# Generated by Django 3.1.7 on 2021-04-08 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0013_auto_20210407_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('address', models.CharField(max_length=254)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='personal.cart')),
            ],
        ),
    ]
