# Generated by Django 3.1.7 on 2021-05-04 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0014_auto_20210408_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='oder_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Ordered'), (2, 'Underdelivery'), (3, 'Delivered')], default=1),
        ),
    ]
