# Generated by Django 3.1.7 on 2021-05-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0014_auto_20210408_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantprofile',
            name='openTime',
            field=models.TimeField(max_length=50),
        ),
    ]
