# Generated by Django 3.1.7 on 2021-05-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0015_auto_20210504_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantprofile',
            old_name='openTime',
            new_name='open_from',
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='open_to',
            field=models.TimeField(default='00:00', max_length=50),
            preserve_default=False,
        ),
    ]
