# Generated by Django 3.1.7 on 2021-05-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0017_cart_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='available_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='available_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
