# Generated by Django 3.1.7 on 2021-05-04 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0017_cart_restaurant'),
        ('personal', '0015_auto_20210504_2026'),
    ]

    operations = [
    ]
