# Generated by Django 3.1.7 on 2021-05-04 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0018_merge_20210504_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='oder_date',
            new_name='order_date',
        ),
    ]
