# Generated by Django 3.1.7 on 2021-05-04 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0018_auto_20210504_1838'),
        ('personal', '0019_auto_20210504_2053'),
    ]

    operations = [
    ]
