# Generated by Django 3.1.7 on 2021-05-05 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0023_order_courier'),
        ('personal', '0023_payments_order'),
    ]

    operations = [
    ]
