# Generated by Django 3.1.7 on 2021-05-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0024_merge_20210505_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='estimated_del_time',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
