# Generated by Django 3.1.7 on 2021-05-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0025_restaurantprofile_estimated_del_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_type',
            field=models.IntegerField(default=1),
        ),
    ]
