# Generated by Django 3.1.7 on 2021-03-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tenant_type',
            field=models.IntegerField(choices=[(1, 'Restaurant'), (2, 'Customer'), (3, 'Courier')], default=2),
        ),
    ]
